version: '3.7'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env 
    container_name: presupuesto-container
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - ./src/core/prisma/tmp/postgres:/var/lib/postgresql13/data
    networks:
      - app-network

  pgadmin:   
    image: dpage/pgadmin4
    container_name: presupuesto-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
    depends_on:
      - db  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

